evals:
  wflow0:
    submission_type: params
    trs_id: dockstore
    version_id: develop
    workflow_id: github.com/dockstore-testing/md5sum-checker
    workflow_type: CWL
  wflow1:
    submission_type: params
    trs_id: dockstore
    version_id: develop
    workflow_id: github.com/dockstore-testing/md5sum-checker/wdl
    workflow_type: WDL
toolregistries:
  dockstore:
    auth: ''
    host: dockstore.org:8443
    proto: https
workflowservices:
  arvados-wes:
    auth: ''
    auth_type: ''
    host: wes.qr1hi.arvadosapi.com
    proto: http
  hca-cromwell:
    auth: ''
    auth_type: ''
    host: g0n2qjnu94.execute-api.us-east-1.amazonaws.com/test
    proto: http
  local:
    auth: ''
    auth_type: ''
    host: 0.0.0.0:8080
    proto: http
